repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        args: ['--line-length', '88']
        language_version: python3

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest before commit
        entry: poetry run pytest
        language: system
        types: [python]
