FROM python:3.12-slim

WORKDIR /src

COPY pyproject.toml poetry.lock* ./

RUN pip install --upgrade pip && \
    pip install poetry &&\
    pip install debugpy

RUN poetry config virtualenvs.create false
RUN poetry install --without dev --no-interaction --no-ansi --no-root

COPY app/ /src/app/

CMD ["sh", "-c", "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"]
